FROM adoptopenjdk/openjdk11:latest

RUN apt-get update && apt-get install maven -y
# Create app directory 
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY target/demo-0.0.1-SNAPSHOT.jar /usr/src/app/spring-app.jar
	